name: Build macOS App & DMG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install py2app

    - name: Build .app with py2app
      run: |
        python3 setup.py py2app

    - name: Create DMG
      run: |
        hdiutil create -volname "HTML Generator" -srcfolder dist/html_generator.app -ov -format UDZO html_generator.dmg

    - name: Upload DMG as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: html_generator.dmg
        path: html_generator.dmg
